# This file was generated by GoReleaser. DO NOT EDIT.
class Mprod < Formula
  desc ""
  homepage ""
  version "0.0.0-rc1"
  bottle :unneeded

  if OS.mac?
    url "https://releases.velocity.tech/mprod/v0.0.0-rc1/mprod_0.0.0-rc1_Darwin_x86_64.tar.gz"
    sha256 "3227c790132f1a3bcfb7f3db573120ca8217457e6a8ac052f02578870bb1d645"
  end

  def install
    bin.install "program"
  end

  test do
    system "#{bin}/mprod version"
  end
end
