# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mprod < Formula
  desc ""
  homepage ""
  version "0.0.0-rc2"
  bottle :unneeded

  if OS.mac?
    url "https://releases.velocity.tech/mprod/v0.0.0-rc2/mprod_0.0.0-rc2_Darwin_x86_64.tar.gz"
    sha256 "ddc5d5e490389327100cefccfb60dc41d44310e6524df6c499a8232a8165a196"
  end

  def install
    bin.install "program"
  end

  test do
    system "#{bin}/mprod version"
  end
end
