# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VelocityATdev < Formula
  desc ""
  homepage "https://velocity.tech"
  version "0.0.1-rc10-357031d-20230405074041-7802b8f-20230405074325-b6810c0-20230405074844"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.velocity.tech/velocity/v0.0.1-rc10-357031d-20230405074041-7802b8f-20230405074325-b6810c0-20230405074844/velocity_Darwin_x86_64.tar.gz"
      sha256 "0bee106899f4e342f6e1c5f69e1e5ca0b61ca25cdcafb02e234c1fc120c51563"

      def install
        bin.install "velocity"

        system bin/"velocity completion bash > bash_completion.bash"
        bash_completion.install "bash_completion.bash" => "velocity"

        system bin/"velocity completion zsh > zsh_completion.zsh"
        zsh_completion.install "zsh_completion.zsh" => "_velocity"

        system bin/"velocity completion fish > fish_completion.fish"
        fish_completion.install "fish_completion.fish" => "velocity.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.velocity.tech/velocity/v0.0.1-rc10-357031d-20230405074041-7802b8f-20230405074325-b6810c0-20230405074844/velocity_Darwin_arm64.tar.gz"
      sha256 "d96501587ba27cb8065179454ffd82f5d7f923876e9de94a9e909ae77edd49f1"

      def install
        bin.install "velocity"

        system bin/"velocity completion bash > bash_completion.bash"
        bash_completion.install "bash_completion.bash" => "velocity"

        system bin/"velocity completion zsh > zsh_completion.zsh"
        zsh_completion.install "zsh_completion.zsh" => "_velocity"

        system bin/"velocity completion fish > fish_completion.fish"
        fish_completion.install "fish_completion.fish" => "velocity.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.velocity.tech/velocity/v0.0.1-rc10-357031d-20230405074041-7802b8f-20230405074325-b6810c0-20230405074844/velocity_Linux_arm64.tar.gz"
      sha256 "e9a7022bed0f6dd8c4aa84550e87e6b2398266cac68c6d61c856bcae338155a5"

      def install
        bin.install "velocity"

        system bin/"velocity completion bash > bash_completion.bash"
        bash_completion.install "bash_completion.bash" => "velocity"

        system bin/"velocity completion zsh > zsh_completion.zsh"
        zsh_completion.install "zsh_completion.zsh" => "_velocity"

        system bin/"velocity completion fish > fish_completion.fish"
        fish_completion.install "fish_completion.fish" => "velocity.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://releases.velocity.tech/velocity/v0.0.1-rc10-357031d-20230405074041-7802b8f-20230405074325-b6810c0-20230405074844/velocity_Linux_x86_64.tar.gz"
      sha256 "ca23ae3f83f528020cf6266adb3240b702e1d1f66475a0e73329865d1d74a440"

      def install
        bin.install "velocity"

        system bin/"velocity completion bash > bash_completion.bash"
        bash_completion.install "bash_completion.bash" => "velocity"

        system bin/"velocity completion zsh > zsh_completion.zsh"
        zsh_completion.install "zsh_completion.zsh" => "_velocity"

        system bin/"velocity completion fish > fish_completion.fish"
        fish_completion.install "fish_completion.fish" => "velocity.fish"
      end
    end
  end

  test do
    system "#{bin}/velocity version"
  end
end
