# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Veloctl < Formula
  desc ""
  homepage "https://velocity.tech"
  version "0.4.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://releases.velocity.tech/veloctl/v0.4.1/veloctl_0.4.1_Darwin_arm64.tar.gz"
      sha256 "470e81df23a224dd7e7bc2454df2429b0a1f1641e106d8c613bf077cca66e30f"

      def install
        bin.install "veloctl"

        system bin/"veloctl completion bash > bash_completion.bash"
        bash_completion.install "bash_completion.bash" => "veloctl"

        system bin/"veloctl completion zsh > zsh_completion.zsh"
        zsh_completion.install "zsh_completion.zsh" => "_veloctl"

        system bin/"veloctl completion fish > fish_completion.fish"
        fish_completion.install "fish_completion.fish" => "veloctl.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://releases.velocity.tech/veloctl/v0.4.1/veloctl_0.4.1_Darwin_x86_64.tar.gz"
      sha256 "b1e4188a777ccec0ea7cbbc18c0cd535cfba2d04acc8b6d84ad17358f1dc45b5"

      def install
        bin.install "veloctl"

        system bin/"veloctl completion bash > bash_completion.bash"
        bash_completion.install "bash_completion.bash" => "veloctl"

        system bin/"veloctl completion zsh > zsh_completion.zsh"
        zsh_completion.install "zsh_completion.zsh" => "_veloctl"

        system bin/"veloctl completion fish > fish_completion.fish"
        fish_completion.install "fish_completion.fish" => "veloctl.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.velocity.tech/veloctl/v0.4.1/veloctl_0.4.1_Linux_arm64.tar.gz"
      sha256 "091f70475cbb8a17e9b76e759501374cdab9c28938da5dbc63fe9a7010b4e90a"

      def install
        bin.install "veloctl"

        system bin/"veloctl completion bash > bash_completion.bash"
        bash_completion.install "bash_completion.bash" => "veloctl"

        system bin/"veloctl completion zsh > zsh_completion.zsh"
        zsh_completion.install "zsh_completion.zsh" => "_veloctl"

        system bin/"veloctl completion fish > fish_completion.fish"
        fish_completion.install "fish_completion.fish" => "veloctl.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://releases.velocity.tech/veloctl/v0.4.1/veloctl_0.4.1_Linux_x86_64.tar.gz"
      sha256 "85c47a89eb3ea9c43c4a70d6dc70e97a9b7d323234edf24462934bdb067139d5"

      def install
        bin.install "veloctl"

        system bin/"veloctl completion bash > bash_completion.bash"
        bash_completion.install "bash_completion.bash" => "veloctl"

        system bin/"veloctl completion zsh > zsh_completion.zsh"
        zsh_completion.install "zsh_completion.zsh" => "_veloctl"

        system bin/"veloctl completion fish > fish_completion.fish"
        fish_completion.install "fish_completion.fish" => "veloctl.fish"
      end
    end
  end

  test do
    system "#{bin}/veloctl version"
  end
end
