# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Veloctl < Formula
  desc ""
  homepage ""
  version "0.0.3"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://releases.velocity.tech/veloctl/v0.0.3/veloctl_0.0.3_Darwin_x86_64.tar.gz"
    sha256 "7a7c1fd82776f3db7fe3d72fc855563e97c8fc4e846f60ebb18bd524899dddd0"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://releases.velocity.tech/veloctl/v0.0.3/veloctl_0.0.3_Linux_x86_64.tar.gz"
    sha256 "47619dc68b225db7750680d0571d89cd56860d4ab0badc19c4f59df0578419cb"
  end

  def install
    bin.install "veloctl"
  end

  test do
    system "#{bin}/veloctl version"
  end
end
