# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Veloctl < Formula
  desc ""
  homepage "https://velocity.tech"
  version "0.5.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://releases.velocity.tech/veloctl/v0.5.2/veloctl_0.5.2_Darwin_arm64.tar.gz"
      sha256 "3832ad5a1aaae53f9fc0ec88f601c11fffea24ecb536813a0e1a484d9546eec2"

      def install
        bin.install "veloctl"

        system bin/"veloctl completion bash > bash_completion.bash"
        bash_completion.install "bash_completion.bash" => "veloctl"

        system bin/"veloctl completion zsh > zsh_completion.zsh"
        zsh_completion.install "zsh_completion.zsh" => "_veloctl"

        system bin/"veloctl completion fish > fish_completion.fish"
        fish_completion.install "fish_completion.fish" => "veloctl.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://releases.velocity.tech/veloctl/v0.5.2/veloctl_0.5.2_Darwin_x86_64.tar.gz"
      sha256 "8735f84e823d20db2a2c24a0c8be9fafb6befc3251483a11b57f9fdc6f397250"

      def install
        bin.install "veloctl"

        system bin/"veloctl completion bash > bash_completion.bash"
        bash_completion.install "bash_completion.bash" => "veloctl"

        system bin/"veloctl completion zsh > zsh_completion.zsh"
        zsh_completion.install "zsh_completion.zsh" => "_veloctl"

        system bin/"veloctl completion fish > fish_completion.fish"
        fish_completion.install "fish_completion.fish" => "veloctl.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.velocity.tech/veloctl/v0.5.2/veloctl_0.5.2_Linux_arm64.tar.gz"
      sha256 "7724d7c190b7cf7d3a7b467f084cb856978ca2584d586ae20466836350c3fc79"

      def install
        bin.install "veloctl"

        system bin/"veloctl completion bash > bash_completion.bash"
        bash_completion.install "bash_completion.bash" => "veloctl"

        system bin/"veloctl completion zsh > zsh_completion.zsh"
        zsh_completion.install "zsh_completion.zsh" => "_veloctl"

        system bin/"veloctl completion fish > fish_completion.fish"
        fish_completion.install "fish_completion.fish" => "veloctl.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://releases.velocity.tech/veloctl/v0.5.2/veloctl_0.5.2_Linux_x86_64.tar.gz"
      sha256 "c558ec9ccebcb6b8134951bf27de4c70fbeafbcf4ac9b8e6421682ce3c66f8bc"

      def install
        bin.install "veloctl"

        system bin/"veloctl completion bash > bash_completion.bash"
        bash_completion.install "bash_completion.bash" => "veloctl"

        system bin/"veloctl completion zsh > zsh_completion.zsh"
        zsh_completion.install "zsh_completion.zsh" => "_veloctl"

        system bin/"veloctl completion fish > fish_completion.fish"
        fish_completion.install "fish_completion.fish" => "veloctl.fish"
      end
    end
  end

  test do
    system "#{bin}/veloctl version"
  end
end
